###
GET http://localhost:3000/ HTTP/1.1

###
GET http://localhost:3000/events HTTP/1.1

###
GET http://localhost:3000/events/66426b3fd3e10217cf2e09be HTTP/1.1

###
POST http://localhost:3000/events/create

###
PUT http://localhost:3000/events/6654ce0974ed61cc8603fabe HTTP/1.1

###
DELETE  http://localhost:3000/events/6654ce0974ed61cc8603fabe



